/* Alone2Lone persistent backend bridge: authenticated API + realtime notifications. */
(function(){
  'use strict';
  const api=async(path,options={})=>{const token=window.a2lAuth?.getAccessToken?.()||'';const headers={'content-type':'application/json'};if(token)headers.authorization=`Bearer ${token}`;const r=await fetch(path,{...options,headers:{...headers,...(options.headers||{})},body:options.body&&typeof options.body!=='string'?JSON.stringify(options.body):options.body});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`HTTP ${r.status}`);return r.json()};
  window.a2lBackend={api,saveProfile:()=>api('/api/profile',{method:'PUT',body:{profile:state.profile}}),friendRequest:to=>api('/api/friend-request',{method:'POST',body:{to}}),report:(to,reason,context)=>api('/api/report',{method:'POST',body:{to,reason,context}}),block:to=>api('/api/block',{method:'POST',body:{to}}),friendResponse:(requestId,accepted)=>api('/api/friend-response',{method:'POST',body:{requestId,accepted}}),chatRequest:to=>api('/api/chat-request',{method:'POST',body:{to}}),chatResponse:(requestId,accepted)=>api('/api/chat-response',{method:'POST',body:{requestId,accepted}}),reconnect:(to,historyId)=>api('/api/reconnect',{method:'POST',body:{to,historyId}}),reconnectResponse:(requestId,accepted)=>api('/api/reconnect-response',{method:'POST',body:{requestId,accepted}}),sendMessage:(to,text)=>api('/api/message',{method:'POST',body:{to,text}}),notifications:()=>api('/api/notifications'),history:()=>api('/api/history'),requests:()=>api('/api/requests'),friends:()=>api('/api/friends'),conversation:to=>api('/api/conversation?to='+encodeURIComponent(to)),me:()=>api('/api/me')};
  async function syncIdentity(){try{const me=await window.a2lBackend.me();if(me){state.profile={...state.profile,...me};save();if(typeof renderProfile==='function')renderProfile();}}catch(e){console.warn('identity sync:',e.message)}}
  function backendSaveProfile(){window.a2lBackend.saveProfile().catch(e=>console.warn('profile persistence:',e.message))}
  async function boot(){await window.a2lAuthReady?.catch?.(()=>{});if(!window.a2lAuth?.getAccessToken?.())return;await syncIdentity();backendSaveProfile();await hydrateRequests();await hydrateFriends();loadNotifications();}
  async function hydrateFriends(){try{const rows=await window.a2lBackend.friends();for(const r of rows||[]){if(!r?.a2lId||friends.some(f=>f.a2lId===r.a2lId))continue;friends.push({id:Math.floor(Math.random()*900000000)+100000000,name:r.displayName,a2lId:r.a2lId,avatar:r.avatar||'🙂',ageGroup:r.ageGroup||'',languages:r.languages||[],online:true,interests:r.interests||[],bio:''});}if(typeof renderPeople==='function')renderPeople();if(typeof renderProfile==='function')renderProfile();}catch(e){}}
  async function hydrateRequests(){try{const data=await window.a2lBackend.requests();for(const r of data.friends||[]){if(r.to_user===state.profile.a2lId)state.connectionRequests[r.id]=r;else state.outgoingConnectionRequests[r.to_user]=r;}for(const r of data.chats||[]){state.chatRequests[r.id]=r;}save();if(typeof renderChats==='function')renderChats();}catch(e){}}
  document.addEventListener('DOMContentLoaded',()=>{if(typeof save==='function'&&!window.__a2lSaveWrapped){const oldSave=window.save;window.save=function(){oldSave();if(window.a2lAuth?.getAccessToken?.())backendSaveProfile()};window.__a2lSaveWrapped=true;}boot();});
  window.addEventListener('a2l:auth',e=>{if(e.detail?.session)boot();});
  async function loadNotifications(){try{const rows=await window.a2lBackend.notifications();window.__a2lNotifications=rows||[];const unread=(rows||[]).filter(x=>!x.read_at).length;if(unread)toast(`${unread} new notification${unread===1?'':'s'} 🔔`)}catch(e){}}
  window.addEventListener('a2l:notification',e=>{const n=e.detail||{};const t=n.type||'';if(t==='message')toast('New message 💬');else if(t==='friend_request')toast('New friend request 🤝');else if(t==='reconnect_request')toast('Someone wants to reconnect 🔄');else if(t==='chat_request')toast('New chat request 📩');loadNotifications();});
})();
