/* A2L shared live-match/call UI. Local media is real; production cross-device signaling plugs into the signaling hook. */
(function(){
  "use strict";
  let stream=null,pc=null,targetId=null,mode=null,source="call",facing="user",muted=false,cameraOn=true,audioCtx=null,analyser=null,raf=0,inCall=false;
  const channel=('BroadcastChannel' in window)?new BroadcastChannel('a2l-live-signal'):null;
  const peerId=(()=>{let x=sessionStorage.getItem('a2lLivePeer');if(!x){x='p_'+Math.random().toString(36).slice(2)+Date.now();sessionStorage.setItem('a2lLivePeer',x)}return x})();
  const friend=()=>friends.find(f=>Number(f.id)===Number(targetId));
  const setText=(id,t)=>{const x=$(id);if(x)x.textContent=t};
  const online=()=>!!friend()?.online;
  const canCall=()=>online();
  function showChooser(nameOrId,idMaybe){const id=idMaybe===undefined?nameOrId:idMaybe;targetId=Number(id);const f=friend();setText('chatCallTitle',`Call ${f?.name||'user'}`);setText('chatCallSub',online()?'Choose voice or video.':'This user is offline.');const c=$('callChooser');if(c)c.hidden=!online();setText('callHint',online()?'Calls are online-only. Live media is not recorded or stored.':'Offline users do not receive queued or missed-call notifications.');openModal('chatCallModal');}
  async function getMedia(kind){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera/microphone access is not supported here.');return navigator.mediaDevices.getUserMedia(kind==='video'?{audio:true,video:{facingMode:facing}}:{audio:true,video:false});}
  function setPresence(status){state.liveStatus=status;save();try{localStorage.setItem("a2lPresence_"+state.profile.a2lId,JSON.stringify({status,at:Date.now()}))}catch(_e){}}
  function stop(){setPresence("online");cancelAnimationFrame(raf);raf=0;if(audioCtx){audioCtx.close().catch(()=>{});audioCtx=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(pc){try{pc.close()}catch(_e){}pc=null}targetId=null;mode=null;muted=false;cameraOn=true;const m=$('matchSessionModal');if(m){m.classList.remove('show');m.setAttribute('aria-hidden','true')}if($('reactionPicker'))$('reactionPicker').hidden=true;}
  function renderBase(kind,id,src){
    const f=friend();setText('matchSessionTitle',kind==='video'?'Video Match':'Voice Match');setText('matchSessionStatus',src==='quick'?'Quick Match · LIVE':src==='vibe'?'Find Your Vibe · LIVE':'Live call · LIVE');
    setText('remoteMatchName',f?.name||'A2L user');setText('remoteMatchAvatar',f?.avatar||'🙂');setText('voiceRemoteName',f?.name||'A2L user');setText('voiceRemoteAvatar',f?.avatar||'🙂');
    setText('localMatchAvatar',state.profile.avatar||'💻');setText('voiceLocalAvatar',state.profile.avatar||'💻');
    $('videoMatchArea').hidden=kind!=='video';$('voiceMatchArea').hidden=kind!=='voice';$('videoControls').hidden=kind!=='video';$('voiceControls').hidden=kind!=='voice';
    $('remoteFallback').hidden=false;$('remoteMatchVideo').hidden=true;$('localFallback').hidden=kind==='video';$('localMatchVideo').hidden=kind!=='video';
    const modal=$('matchSessionModal');modal.classList.add('show');modal.setAttribute('aria-hidden','false');
  }
  function setupAudioMeter(){if(!stream?.getAudioTracks().length)return;try{audioCtx=new (window.AudioContext||window.webkitAudioContext)();const src=audioCtx.createMediaStreamSource(stream);analyser=audioCtx.createAnalyser();analyser.fftSize=256;src.connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);const tick=()=>{if(!analyser)return;analyser.getByteFrequencyData(data);let sum=0;for(const n of data)sum+=n;const level=Math.min(1,sum/data.length/80);$('localAudioRing')?.style.setProperty('--audio-level',String(level));raf=requestAnimationFrame(tick)};tick()}catch(_e){}}
  async function startMatch(kind,id,src){targetId=Number(id);source=src||'call';if(!canCall()){toast(online()?'Calling is not allowed by this user.':'User is offline — no call notification was sent.');targetId=null;return;}mode=kind;setPresence(source==="quick"?"quick_match":"in_call");renderBase(kind,id,source);setText('matchSessionStatus',`Starting ${kind}…`);try{stream=await getMedia(kind);if(kind==='video'){const v=$('localMatchVideo');v.srcObject=stream;v.hidden=false;$('localFallback').hidden=true;setText('localMatchMeta','Camera on · Mic on')}else{setText('voiceLocalMeta','Mic on · listening');setupAudioMeter()}setText('matchSessionStatus',source==='quick'?'Quick Match · Connected':source==='vibe'?'Find Your Vibe · Connected':'Connected');setupPeer();inCall=true;channel?.postMessage({type:"call-invite",to:friend()?.a2lId,from:state.profile.a2lId,fromName:state.profile.displayName,fromAvatar:state.profile.avatar,kind,targetId:state.profile.a2lId,source});}catch(e){toast(e.message||'Microphone/camera permission is required.');stop();}}
  function setupPeer(){if(!window.RTCPeerConnection)return;pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream?.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{const v=$('remoteMatchVideo');if(v&&mode==='video'){v.srcObject=e.streams[0];v.hidden=false;$('remoteFallback').hidden=true;} };pc.onconnectionstatechange=()=>{if(pc?.connectionState==='connected')setText('matchSessionStatus','Connected · LIVE');if(['failed','closed'].includes(pc?.connectionState))setText('matchSessionStatus','Connection ended');};}
  function toggleMute(){if(!stream)return;muted=!muted;stream.getAudioTracks().forEach(t=>t.enabled=!muted);setText('matchMute',muted?'🔇':'🎙️');setText('voiceMute',muted?'🔇':'🎙️');setText('voiceLocalMeta',muted?'Mic muted':'Mic on · listening');}
  async function toggleCamera(){if(mode!=='video')return;cameraOn=!cameraOn;if(stream){stream.getVideoTracks().forEach(t=>t.enabled=cameraOn)}$('localMatchVideo').hidden=!cameraOn;$('localFallback').hidden=cameraOn;setText('matchCamera',cameraOn?'📹':'🚫');setText('localMatchMeta',cameraOn?'Camera on · Mic '+(muted?'off':'on'):'Camera off · voice continues');}
  async function switchCamera(){if(mode!=='video'||!cameraOn)return;facing=facing==='user'?'environment':'user';try{const ns=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:facing}});const nt=ns.getVideoTracks()[0],old=stream?.getVideoTracks()[0];if(old){stream.removeTrack(old);old.stop()}stream?.addTrack(nt);const sender=pc?.getSenders().find(s=>s.track?.kind==='video');if(sender)await sender.replaceTrack(nt);$('localMatchVideo').srcObject=stream;toast(facing==='user'?'Front camera':'Back camera');}catch(_e){toast('Could not switch camera.');}}
  function switchMode(){const next=mode==='video'?'voice':'video';startMatch(next,targetId,source);}
  function react(emoji){const layer=$('matchReactionLayer');if(!layer)return;const el=document.createElement('span');el.className='a2l-live-reaction';el.textContent=emoji;el.style.left=(25+Math.random()*50)+'%';el.style.top=(55+Math.random()*20)+'%';layer.appendChild(el);setTimeout(()=>el.remove(),1200);if($('reactionPicker'))$('reactionPicker').hidden=true;}
  function more(){openModal('matchMoreModal');setText('matchMoreSub',friend()?`Options for ${friend().name}`:'Safety and connection options');}
  function addFriend(){if(targetId)requestConnection(Number(targetId));}
  channel?.addEventListener("message",e=>{const m=e.data||{};if(m.type!=="call-invite"||m.to!==state.profile.a2lId)return;const cp=state.privacy||{};if(cp.call==="nobody"||(cp.call==="connected"&&!((state.connections||[]).map(Number).includes(Number(friends.find(x=>x.a2lId===m.from)?.id))))){channel.postMessage({type:"call-declined",to:m.from,from:state.profile.a2lId});return}if(state.liveStatus==="in_call"){channel.postMessage({type:"call-busy",to:m.from,from:state.profile.a2lId});return}if(state.liveStatus==="quick_match"){channel.postMessage({type:"call-quick-busy",to:m.from,from:state.profile.a2lId});return}const accept=confirm(`${m.fromName||"A2L user"} is calling you for a ${m.kind==="video"?"video":"voice"} call.

Accept?`);if(accept){const f=friends.find(x=>x.a2lId===m.from);if(f)startMatch(m.kind,f.id,"call");else toast("Caller profile is not available in this demo.")}else{channel.postMessage({type:"call-declined",to:m.from,from:state.profile.a2lId})}});channel?.addEventListener("message",e=>{const m=e.data||{};if(m.to!==state.profile.a2lId)return;if(m.type==="call-busy")setText("matchSessionStatus","User is busy on another call");if(m.type==="call-quick-busy")setText("matchSessionStatus","User is currently in Quick Match");if(m.type==="call-declined")setText("matchSessionStatus","Call declined")});
  window.a2lCall={showCallModal:showChooser,startMatch,reset:stop};
  document.addEventListener('DOMContentLoaded',()=>{setPresence('online');window.addEventListener('beforeunload',()=>{try{localStorage.removeItem('a2lPresence_'+state.profile.a2lId)}catch(_e){}});
    $('startVideoCall')?.addEventListener('click',()=>{closeModal('chatCallModal');startMatch('video',targetId,'call')});
    $('startVoiceCall')?.addEventListener('click',()=>{closeModal('chatCallModal');startMatch('voice',targetId,'call')});
    $('chatCallClose')?.addEventListener('click',()=>closeModal('chatCallModal'));
    $('matchEnd')?.addEventListener('click',stop);$('voiceEnd')?.addEventListener('click',stop);$('matchBack')?.addEventListener('click',stop);
    $('matchMute')?.addEventListener('click',toggleMute);$('voiceMute')?.addEventListener('click',toggleMute);$('matchCamera')?.addEventListener('click',toggleCamera);$('matchSwitchCamera')?.addEventListener('click',switchCamera);$('matchVoiceSwitch')?.addEventListener('click',switchMode);$('voiceVideoSwitch')?.addEventListener('click',switchMode);
    $('matchReaction')?.addEventListener('click',()=>{$('reactionPicker').hidden=!$('reactionPicker').hidden});$('voiceReaction')?.addEventListener('click',()=>{$('reactionPicker').hidden=!$('reactionPicker').hidden});qsa('#reactionPicker button').forEach(b=>b.addEventListener('click',()=>react(b.textContent)));
    $('matchMore')?.addEventListener('click',more);$('matchMoreClose')?.addEventListener('click',()=>closeModal('matchMoreModal'));$('matchConnect')?.addEventListener('click',()=>{closeModal('matchMoreModal');addFriend()});$('matchReport')?.addEventListener('click',()=>{closeModal('matchMoreModal');if(targetId)reportPerson(targetId)});$('matchBlock')?.addEventListener('click',()=>{const id=targetId;closeModal('matchMoreModal');if(id)blockPerson(id);stop()});$('matchAddFriend')?.addEventListener('click',addFriend);$('voiceAddFriend')?.addEventListener('click',addFriend);
  });
})();
