/* Alone2Lone real cross-device WebRTC calls. Media is P2P; this server only relays signaling. */
(function(){
"use strict";
let stream=null,pc=null,targetId=null,mode=null,source="call",facing="user",muted=false,cameraOn=true,audioCtx=null,analyser=null,raf=0,inCall=false,initiator=false,signalSocket=null,iceQueue=[];
const friend=()=>friends.find(f=>Number(f.id)===Number(targetId));
const setText=(id,t)=>{const x=$(id);if(x)x.textContent=t};
const online=()=>!!friend()?.online;
function wsUrl(){return (location.protocol==='https:'?'wss://':'ws://')+location.host;}
function ensureSocket(){if(signalSocket&&[0,1].includes(signalSocket.readyState))return signalSocket;signalSocket=new WebSocket(wsUrl());signalSocket.onopen=()=>{send({type:'register',a2lId:state.profile.a2lId});};signalSocket.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}handleSignal(m)};signalSocket.onclose=()=>{signalSocket=null};return signalSocket;}
function send(m){if(signalSocket?.readyState===1)signalSocket.send(JSON.stringify(m));}
function showChooser(nameOrId,idMaybe){const id=idMaybe===undefined?nameOrId:idMaybe;targetId=Number(id);const f=friend();setText('chatCallTitle',`Call ${f?.name||'user'}`);setText('chatCallSub',online()?'Choose voice or video.':'This user is offline.');const c=$('callChooser');if(c)c.hidden=!online();setText('callHint',online()?'Calls are online-only. Live media is not recorded or stored.':'Offline users do not receive queued or missed-call notifications.');openModal('chatCallModal');}
async function getMedia(kind){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera/microphone access is not supported here.');return navigator.mediaDevices.getUserMedia(kind==='video'?{audio:true,video:{facingMode:facing}}:{audio:true,video:false});}
function setPresence(status){state.liveStatus=status;save();try{localStorage.setItem('a2lPresence_'+state.profile.a2lId,JSON.stringify({status,at:Date.now()}))}catch(_){} }
function stop(){send({type:'hangup',to:friend()?.a2lId});setPresence('online');cancelAnimationFrame(raf);raf=0;if(audioCtx){audioCtx.close().catch(()=>{});audioCtx=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(pc){try{pc.close()}catch(_){}pc=null}targetId=null;mode=null;muted=false;cameraOn=true;inCall=false;initiator=false;iceQueue=[];const m=$('matchSessionModal');if(m){m.classList.remove('show');m.setAttribute('aria-hidden','true')}if($('reactionPicker'))$('reactionPicker').hidden=true;}
function renderBase(kind,id,src){const f=friend();setText('matchSessionTitle',kind==='video'?'Video Match':'Voice Match');setText('matchSessionStatus',src==='quick'?'Quick Match · LIVE':src==='vibe'?'Find Your Vibe · LIVE':'Live call · LIVE');setText('remoteMatchName',f?.name||'A2L user');setText('remoteMatchAvatar',f?.avatar||'🙂');setText('voiceRemoteName',f?.name||'A2L user');setText('voiceRemoteAvatar',f?.avatar||'🙂');setText('localMatchAvatar',state.profile.avatar||'💻');setText('voiceLocalAvatar',state.profile.avatar||'💻');$('videoMatchArea').hidden=kind!=='video';$('voiceMatchArea').hidden=kind!=='voice';$('videoControls').hidden=kind!=='video';$('voiceControls').hidden=kind!=='voice';$('remoteFallback').hidden=false;$('remoteMatchVideo').hidden=true;$('localFallback').hidden=kind==='video';$('localMatchVideo').hidden=kind!=='video';const modal=$('matchSessionModal');modal.classList.add('show');modal.setAttribute('aria-hidden','false');}
function setupAudioMeter(){if(!stream?.getAudioTracks().length)return;try{audioCtx=new (window.AudioContext||window.webkitAudioContext)();const src=audioCtx.createMediaStreamSource(stream);analyser=audioCtx.createAnalyser();analyser.fftSize=256;src.connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);const tick=()=>{if(!analyser)return;analyser.getByteFrequencyData(data);let sum=0;for(const n of data)sum+=n;const level=Math.min(1,sum/data.length/80);$('localAudioRing')?.style.setProperty('--audio-level',String(level));raf=requestAnimationFrame(tick)};tick()}catch(_){} }
function setupPeer(){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]});stream?.getTracks().forEach(t=>pc.addTrack(t,stream));pc.onicecandidate=e=>{if(e.candidate)send({type:'ice',to:friend()?.a2lId,candidate:e.candidate});};pc.ontrack=e=>{const v=$('remoteMatchVideo');if(v&&mode==='video'){v.srcObject=e.streams[0];v.hidden=false;$('remoteFallback').hidden=true;}};pc.onconnectionstatechange=()=>{if(pc?.connectionState==='connected')setText('matchSessionStatus','Connected · LIVE');if(['failed','closed','disconnected'].includes(pc?.connectionState))setText('matchSessionStatus','Connection ended');};}
async function flushIce(){for(const c of iceQueue.splice(0)){try{await pc.addIceCandidate(c)}catch(_){} }}
async function startMatch(kind,id,src,isInitiator=true){targetId=Number(id);source=src||'call';if(!friend()){toast('User profile is not available.');return}if(!isInitiator&&!online()){setText('matchSessionStatus','Caller connected');}mode=kind;initiator=isInitiator;setPresence(source==='quick'?'quick_match':'in_call');renderBase(kind,id,source);setText('matchSessionStatus',isInitiator?`Starting ${kind}…`:'Incoming call…');try{stream=await getMedia(kind);if(kind==='video'){$('localMatchVideo').srcObject=stream;$('localMatchVideo').hidden=false;$('localFallback').hidden=true;setText('localMatchMeta','Camera on · Mic on')}else{setText('voiceLocalMeta','Mic on · listening');setupAudioMeter()}setupPeer();inCall=true;ensureSocket();if(isInitiator){setTimeout(async()=>{const offer=await pc.createOffer();await pc.setLocalDescription(offer);send({type:'offer',to:friend().a2lId,sdp:offer,kind,source});},100);}}catch(e){toast(e.message||'Microphone/camera permission is required.');stop();}}
async function handleSignal(m){if(m.type==='registered'||m.type==='replaced')return;if(m.type==='call-invite'){const f=friends.find(x=>x.a2lId===m.from);if(!f)return;const cp=state.privacy||{};if(cp.call==='nobody'){send({type:'call-declined',to:m.from});return}if(state.liveStatus==='in_call'||state.liveStatus==='quick_match'){send({type:'call-busy',to:m.from});return}targetId=Number(f.id);const accept=confirm(`${m.fromName||f.name||'A2L user'} is calling you for a ${m.kind==='video'?'video':'voice'} call.\n\nAccept?`);if(accept){await startMatch(m.kind,f.id,m.source||'call',false);send({type:'call-accept',to:m.from});}else send({type:'call-declined',to:m.from});return}if(m.type==='call-accept'){setText('matchSessionStatus','Accepted · connecting…');return}if(m.type==='call-declined'){setText('matchSessionStatus','Call declined');return}if(m.type==='call-busy'){setText('matchSessionStatus','User is busy');return}if(m.type==='offer'){if(!pc||!inCall){const f=friends.find(x=>x.a2lId===m.from);if(!f)return;await startMatch(m.kind,f.id,m.source||'call',false)}await pc.setRemoteDescription(m.sdp);await flushIce();const ans=await pc.createAnswer();await pc.setLocalDescription(ans);send({type:'answer',to:m.from,sdp:ans});return}if(m.type==='answer'&&pc){await pc.setRemoteDescription(m.sdp);await flushIce();return}if(m.type==='ice'&&pc){if(pc.remoteDescription)try{await pc.addIceCandidate(m.candidate)}catch(_){}else iceQueue.push(m.candidate);return}if(m.type==='hangup'){setText('matchSessionStatus','Call ended');setTimeout(stop,400);}}
function toggleMute(){if(!stream)return;muted=!muted;stream.getAudioTracks().forEach(t=>t.enabled=!muted);setText('matchMute',muted?'🔇':'🎙️');setText('voiceMute',muted?'🔇':'🎙️');setText('voiceLocalMeta',muted?'Mic muted':'Mic on · listening');}
async function toggleCamera(){if(mode!=='video')return;cameraOn=!cameraOn;if(stream)stream.getVideoTracks().forEach(t=>t.enabled=cameraOn);$('localMatchVideo').hidden=!cameraOn;$('localFallback').hidden=cameraOn;setText('matchCamera',cameraOn?'📹':'🚫');setText('localMatchMeta',cameraOn?'Camera on · Mic '+(muted?'off':'on'):'Camera off · voice continues');}
async function switchCamera(){if(mode!=='video'||!cameraOn)return;facing=facing==='user'?'environment':'user';try{const ns=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:facing}});const nt=ns.getVideoTracks()[0],old=stream?.getVideoTracks()[0];if(old){stream.removeTrack(old);old.stop()}stream?.addTrack(nt);const sender=pc?.getSenders().find(s=>s.track?.kind==='video');if(sender)await sender.replaceTrack(nt);$('localMatchVideo').srcObject=stream;toast(facing==='user'?'Front camera':'Back camera');}catch(_){toast('Could not switch camera.');}}
function switchMode(){const next=mode==='video'?'voice':'video';const id=targetId;stop();startMatch(next,id,source,true);}
function react(emoji){const layer=$('matchReactionLayer');if(!layer)return;const el=document.createElement('span');el.className='a2l-live-reaction';el.textContent=emoji;el.style.left=(25+Math.random()*50)+'%';el.style.top=(55+Math.random()*20)+'%';layer.appendChild(el);setTimeout(()=>el.remove(),1200);if($('reactionPicker'))$('reactionPicker').hidden=true;}
function more(){openModal('matchMoreModal');setText('matchMoreSub',friend()?`Options for ${friend().name}`:'Safety and connection options');}
function addFriend(){if(targetId)requestConnection(Number(targetId));}
window.a2lCall={showCallModal:showChooser,startMatch,reset:stop};
document.addEventListener('DOMContentLoaded',()=>{ensureSocket();setPresence('online');window.addEventListener('beforeunload',()=>{send({type:'hangup',to:friend()?.a2lId});try{localStorage.removeItem('a2lPresence_'+state.profile.a2lId)}catch(_){} });$('startVideoCall')?.addEventListener('click',()=>{closeModal('chatCallModal');startMatch('video',targetId,'call',true)});$('startVoiceCall')?.addEventListener('click',()=>{closeModal('chatCallModal');startMatch('voice',targetId,'call',true)});$('chatCallClose')?.addEventListener('click',()=>closeModal('chatCallModal'));$('matchEnd')?.addEventListener('click',stop);$('voiceEnd')?.addEventListener('click',stop);$('matchBack')?.addEventListener('click',stop);$('matchMute')?.addEventListener('click',toggleMute);$('voiceMute')?.addEventListener('click',toggleMute);$('matchCamera')?.addEventListener('click',toggleCamera);$('matchSwitchCamera')?.addEventListener('click',switchCamera);$('matchVoiceSwitch')?.addEventListener('click',switchMode);$('voiceVideoSwitch')?.addEventListener('click',switchMode);$('matchReaction')?.addEventListener('click',()=>{$('reactionPicker').hidden=!$('reactionPicker').hidden});$('voiceReaction')?.addEventListener('click',()=>{$('reactionPicker').hidden=!$('reactionPicker').hidden});qsa('#reactionPicker button').forEach(b=>b.addEventListener('click',()=>react(b.textContent)));$('matchMore')?.addEventListener('click',more);$('matchMoreClose')?.addEventListener('click',()=>closeModal('matchMoreModal'));$('matchConnect')?.addEventListener('click',()=>{closeModal('matchMoreModal');addFriend()});$('matchReport')?.addEventListener('click',()=>{closeModal('matchMoreModal');if(targetId)reportPerson(targetId)});$('matchBlock')?.addEventListener('click',()=>{const id=targetId;closeModal('matchMoreModal');if(id)blockPerson(id);stop()});$('matchAddFriend')?.addEventListener('click',addFriend);$('voiceAddFriend')?.addEventListener('click',addFriend);});
})();
